# Generated by Django 4.2.7 on 2023-11-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='review',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
