# Generated by Django 4.2.7 on 2023-11-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='review/%Y/%m/%d/'),
        ),
    ]
