# Generated by Django 4.2.7 on 2023-11-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
