# Generated by Django 4.2.7 on 2023-11-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0002_rename_review_reply_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='article',
            new_name='review',
        ),
    ]
