# Generated by Django 4.2.7 on 2023-11-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=100)),
                ('content', models.TextField(blank=True)),
                ('document_file', models.FileField(null=True, upload_to='documents/%Y/%m/%d/')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
