# Generated by Django 4.2.7 on 2023-11-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverletter',
            old_name='company',
            new_name='user',
        ),
    ]
