# Generated by Django 4.2.7 on 2023-11-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverletter',
            old_name='cv_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
