# Generated by Django 4.2.7 on 2023-11-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='document_type',
            field=models.CharField(choices=[('A', '1')], max_length=100),
        ),
    ]
