# Generated by Django 4.2.7 on 2023-11-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='document_file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
