# Generated by Django 4.2.7 on 2023-11-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True),
        ),
    ]
