# Generated by Django 4.2.7 on 2023-11-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0002_alter_coverletter_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
