# Generated by Django 4.2.7 on 2023-11-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='document_type',
            field=models.CharField(choices=[('1', '성장 과정'), ('2', '장점과 단점'), ('3', '지원 동기'), ('4', '입사 후 포부')], max_length=100),
        ),
    ]
