# Generated by Django 4.2.7 on 2023-11-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='document_type',
            field=models.IntegerField(choices=[(1, '지원 동기'), (2, '입사 포부'), (3, '성격'), (4, '팀워크'), (5, '기타')]),
        ),
    ]
