# Generated by Django 4.2.7 on 2023-11-24 06:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coverletter_site', '0002_like_coverletter_like_user_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='coverletter',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'coverletter')},
        ),
    ]
