# Generated by Django 4.2.7 on 2023-11-25 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0003_alter_coverletter_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='document_file',
        ),
        migrations.CreateModel(
            name='CoverLetterPlagiarism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_sentence', models.TextField()),
                ('most_similar', models.TextField()),
                ('rate', models.DecimalField(decimal_places=3, max_digits=3, null=True)),
                ('coverletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coverletter_site.coverletter')),
            ],
        ),
    ]
