# Generated by Django 4.2.7 on 2023-11-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0006_alter_coverletterplagiarism_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='document_type',
            field=models.IntegerField(choices=[(1, '지원동기'), (2, '직무선택'), (3, '성격'), (4, '성장과정'), (5, '경험'), (5, '입사 포부'), (5, '팀워크')]),
        ),
    ]
