# Generated by Django 4.2.7 on 2023-11-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0007_alter_coverletter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='document_type',
            field=models.IntegerField(choices=[(1, '지원 동기'), (2, '직무 선택'), (3, '성격'), (4, '성장 과정'), (5, '경험'), (6, '입사 포부'), (7, '팀워크')]),
        ),
    ]
