# Generated by Django 4.2.7 on 2023-11-25 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coverletter_site', '0008_alter_coverletter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
