# Generated by Django 4.2.7 on 2023-11-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletter_site', '0009_alter_coverletter_content_alter_coverletter_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='coverletterplagiarism',
            name='result',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
